version: '2'
services:
  app:
    build: docker/app
    container_name: docusign_app_1
    ports:
     - "8084:80"
    volumes:
     - $PWD:/var/www/html
    environment:
    - APPLICATION_ENV=development
    depends_on:
     - db
    links:
    - db:dev.mysql.fli.com
  db:
    build: docker/local_mysql_db
    container_name: docusign_db_1
    ports:
    - 32774:3306
    environment:
    - MYSQL_DATABASE=test_intranet
    - MYSQL_ALLOW_EMPTY_PASSWORD=true
    - MYSQL_USER=development
    - MYSQL_PASSWORD=development